### ISSUE TITLE
운동시간 자동등록 기능 추가

### ISSUE THREAD

**Issue by gogumaC** [jagaldol/behind-fitness-client#7]
운동 시간이 기록을 추가하고 완료한 시점을 기준으로 자동으로 등록되었으면 좋겠습니다.
기존 : 0~23시까지 중 선택, 운동시간이 오후거나 저녁인 경우 항상 스크롤이 필요합니다.
건의 : 
1. 기록 추가하기 버튼을 누른 시점의 시간을 자동으로 시작시간으로 설정 
2.  완료하기 버튼을 누른 시점을 종료시간으로 자동설정 
3. 기록 화면에서 운동 시간 수정 가능

<img src="https://github.com/jagaldol/behind-fitness-client/assets/59639035/76c24c5c-17ea-414c-8a3c-53c25f56e3bb" width=300px/>
<img src="https://github.com/jagaldol/behind-fitness-client/assets/59639035/cd0cf48d-cc3e-40a3-8770-2a7d041a899a" width=300px/>

**Comment by jagaldol** [comment]
위의 기능을 추가하게 되면 단순 기록의 측면에서 운동에 대한 실시간 측정이 부각되는 것 같습니다.

따라서 기록 추가하기 모달에서 종료시간 `TimeSelector`를 삭제하고 모달이 생성되는 현재 시간에 맞춰 반올림으로 시작시간을 세팅해주는 건 어떨까요

또한, 기록 수정하기 페이지에서 `확인` 버튼을 눌렀을 때 종료 시간이 설정되는 건 문제가 될 것 같습니다. 운동 종료 이후에도 기록에 대한 수정을 할 수 있으니 페이지 접근 후 빠져나오기 위해 `확인`을 클릭 시 종료시간이 변경되버리면 문제가 발생합니다.

`확인`의 이름을 변경하던지 차라리 `확인` 버튼 외에 종료시간 밑에 운동종료 버튼을 추가하는 것은 어떨까요? 클릭 시 종료시간이 버튼 클릭 시점으로 설정되게 하는 겁니다.

**Comment by gogumaC** [comment]
> 위의 기능을 추가하게 되면 단순 기록의 측면에서 운동에 대한 실시간 측정이 부각되는 것 같습니다.
> 
> 따라서 기록 추가하기 모달에서 종료시간 `TimeSelector`를 삭제하고 모달이 생성되는 현재 시간에 맞춰 반올림으로 시작시간을 세팅해주는 건 어떨까요

 - 좋은 방법인것 같습니다!

> 또한, 기록 수정하기 페이지에서 `확인` 버튼을 눌렀을 때 종료 시간이 설정되는 건 문제가 될 것 같습니다. 운동 종료 이후에도 기록에 대한 수정을 할 수 있으니 페이지 접근 후 빠져나오기 위해 `확인`을 클릭 시 종료시간이 변경되버리면 문제가 발생합니다.
>
> `확인`의 이름을 변경하던지 차라리 `확인` 버튼 외에 종료시간 밑에 운동종료 버튼을 추가하는 것은 어떨까요? 클릭 시 종료시간이 버튼 클릭 시점으로 설정되게 하는 겁니다.

- 이부분은 생각을 못했네요. 종료시간 기록이 없을때에 한해서 다이얼로그를 띄워서 해당시간을 종료시간으로 설정할지 물어보는 플로우도 좋을것 같습니다!

**Comment by jagaldol** [comment]
커스텀 confirm을 구현할까 했지만 일이 과하게 커지는 것 같아 browser의 내장 confirm 창을 활용하여 구현 완료 하였습니다.
