### ISSUE TITLE
이슈 및 PR 템플릿 생성

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/behind-fitness-client#8]
이슈 작성에 있어 정형화된 구조가 필요합니다.

이슈에 필요한 타입으로 `버그 리포트`, `기능 추가 토의`, `개발 사항` 이 있을 것 같습니다.

**Comment by jagaldol** [comment]
시간날 때 만들어주시면 감사할 것 같아요

**Comment by gogumaC** [comment]
`개발 사항`이슈에서 필요하다고 생각하시는 항목이 있을까요?
